<a href="https://colab.research.google.com/github/0xrakesh/machine-learning-with-tensorflow/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Learning


# Variable
You simply define the value of the tensor and the datatype and you are good to go! It's worth mentioning that usually we deal with tensors of numeric data, it is quite rare to see string tensors.

In [2]:
import tensorflow as tf

In [5]:
string = tf.Variable("Hello",tf.string)
print(string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Hello'>


## Constant
A Variable, which cannot be changed.

In [11]:
t = tf.constant([[1,1],[1,2]]);

## Rank/Degree
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar.

In [3]:
integer = tf.Variable(1,tf.int8)
print(integer)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>


In [15]:
scalar = tf.Variable(1,tf.int8)
one_dim = tf.Variable([1],tf.int8)
two_dim = tf.Variable([['hi','hi'],['hi','hi']], tf.string)
two_dim_dif = tf.Variable([['hi','hi','hi'],['hi','hi','hi']], tf.string)

## Shape

### tf.shape(variable)
How many items having in the each dimensions.
Returns a tensor containing the shape of the input tensor.<br/>

tf.shape returns a 1-D integer tensor representing the shape of input. For a scalar input, the tensor returned has a shape of (0,) and its value is the empty vector (i.e. []).

### variable.shape
tf.shape and Tensor.shape should be identical in eager mode. Within tf.function or within a compat.v1 context, not all dimensions may be known until execution time. Hence, when defining custom layers and models for graph mode, prefer the dynamic tf.shape(x) over the static x.shape.



In [28]:
tf.shape(scalar)

<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [18]:
print(scalar.shape)

()


In [20]:
tf.shape(one_dim)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [22]:
print(one_dim.shape)

(1,)


In [23]:
tf.shape(two_dim)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [24]:
print(two_dim.shape)

(2, 2)


In [25]:
tf.shape(two_dim_dif)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [26]:
print(two_dim_dif.shape)

(2, 3)
